_SKILL_ALIASES = {
    # C / C++ / C# / .NET
    "c sharp": ["c#", "csharp"],
    "c#": ["c sharp", "csharp"],
    "csharp": ["c#", "c sharp"],
    ".net": ["dotnet", "dot net", "asp.net", "aspnet"],
    "dotnet": [".net", "dot net", "asp.net", "aspnet"],
    "dot net": [".net", "dotnet"],
    "asp.net": ["aspnet", ".net", "dotnet"],
    "aspnet": ["asp.net", ".net", "dotnet"],
    "c++": ["cpp", "c plus plus"],
    "cpp": ["c++", "c plus plus"],
    "c plus plus": ["c++", "cpp"],
    # JavaScript / TypeScript / frontend
    "javascript": ["js", "ecmascript"],
    "js": ["javascript", "ecmascript"],
    "typescript": ["ts"],
    "ts": ["typescript"],
    "node.js": ["node", "nodejs"],
    "node": ["node.js", "nodejs"],
    "nodejs": ["node.js", "node"],
    "react": ["react.js", "reactjs"],
    "react.js": ["react", "reactjs"],
    "reactjs": ["react", "react.js"],
    "front end": ["frontend", "front-end"],
    "frontend": ["front end", "front-end"],
    "front-end": ["frontend", "front end"],
    "back end": ["backend", "back-end"],
    "backend": ["back end", "back-end"],
    "back-end": ["backend", "back end"],
    "full stack": ["fullstack", "full-stack"],
    "fullstack": ["full stack", "full-stack"],
    "full-stack": ["full stack", "fullstack"],
    # Python backend
    "fastapi": ["fast api"],
    "fast api": ["fastapi"],
    "django rest framework": ["drf"],
    "drf": ["django rest framework"],
    "sqlalchemy": ["sql alchemy"],
    "sql alchemy": ["sqlalchemy"],
    "pydantic": ["pydantic models"],
    "pytest": ["py.test"],
    "rest api": ["restful api", "rest", "rest/json api"],
    "restful api": ["rest api", "rest", "rest/json api"],
    "rest/json api": ["rest api", "restful api"],
    "api": ["apis"],
    "apis": ["api"],
    "microservice": ["microservices"],
    "microservices": ["microservice"],
    # Databases
    "postgresql": ["postgres", "postgre sql"],
    "postgres": ["postgresql", "postgre sql"],
    "postgre sql": ["postgresql", "postgres"],
    "mysql": ["my sql"],
    "my sql": ["mysql"],
    "sql server": ["mssql", "ms sql server", "microsoft sql server"],
    "mssql": ["sql server", "ms sql server", "microsoft sql server"],
    "ms sql server": ["sql server", "mssql", "microsoft sql server"],
    "microsoft sql server": ["sql server", "mssql", "ms sql server"],
    "sqlite": ["sqlite3"],
    "sqlite3": ["sqlite"],
    "redis": ["redis cache"],
    "mongodb": ["mongo", "mongo db"],
    "mongo": ["mongodb", "mongo db"],
    "mongo db": ["mongodb", "mongo"],
    "dynamodb": ["dynamo db"],
    "dynamo db": ["dynamodb"],
    # DevOps / infra
    "ci/cd": ["cicd", "ci cd", "continuous integration"],
    "cicd": ["ci/cd", "ci cd", "continuous integration"],
    "ci cd": ["ci/cd", "cicd", "continuous integration"],
    "github actions": ["gh actions"],
    "gh actions": ["github actions"],
    "gitlab ci": ["gitlab-ci", "gitlab pipelines"],
    "gitlab-ci": ["gitlab ci", "gitlab pipelines"],
    "gitlab pipelines": ["gitlab ci", "gitlab-ci"],
    "docker": ["containerization", "containers"],
    "docker compose": ["docker-compose", "compose"],
    "docker-compose": ["docker compose"],
    "kubernetes": ["k8s"],
    "k8s": ["kubernetes"],
    "aws": ["amazon web services"],
    "amazon web services": ["aws"],
    "gcp": ["google cloud", "google cloud platform"],
    "google cloud": ["gcp", "google cloud platform"],
    "google cloud platform": ["gcp", "google cloud"],
    "azure": ["microsoft azure"],
    "microsoft azure": ["azure"],
    # Messaging / architecture
    "sqs": ["amazon sqs"],
    "amazon sqs": ["sqs"],
    "kafka": ["apache kafka"],
    "apache kafka": ["kafka"],
    "event driven": ["event-driven", "event-driven architecture"],
    "event-driven": ["event driven", "event-driven architecture"],
    "event-driven architecture": ["event driven", "event-driven"],
    # AI tooling
    "llm": ["llms", "large language model", "large language models"],
    "llms": ["llm", "large language model", "large language models"],
    "large language model": ["llm", "llms"],
    "large language models": ["llm", "llms"],
    "claude": ["anthropic", "anthropic claude"],
    "anthropic": ["claude", "anthropic claude"],
    "claude code": ["anthropic claude code"],
    "github copilot": ["copilot"],
    "copilot": ["github copilot"],
    "model context protocol": ["mcp"],
    "mcp": ["model context protocol"],
    "langchain": ["lang chain"],
    "lang chain": ["langchain"],
    "langgraph": ["lang graph"],
    "lang graph": ["langgraph"],
    # CFD / simulation general
    "cfd": ["computational fluid dynamics"],
    "computational fluid dynamics": ["cfd"],
    "finite volume": ["finite-volume", "fvm", "finite volume method"],
    "finite-volume": ["finite volume", "fvm", "finite volume method"],
    "fvm": ["finite volume", "finite-volume", "finite volume method"],
    "finite volume method": ["finite volume", "finite-volume", "fvm"],
    "reduced order model": ["reduced-order model", "rom"],
    "reduced-order model": ["reduced order model", "rom"],
    "rom": ["reduced order model", "reduced-order model"],
    "proper orthogonal decomposition": ["pod"],
    "pod": ["proper orthogonal decomposition"],
    # OpenFOAM / ANSYS / CFD tools
    "openfoam": ["open foam"],
    "open foam": ["openfoam"],
    "ansys fluent": ["fluent"],
    "fluent": ["ansys fluent"],
    "ansys cfx": ["cfx"],
    "cfx": ["ansys cfx"],
    "icem cfd": ["ansys icem", "ansys icem cfd", "icem"],
    "ansys icem": ["icem cfd", "ansys icem cfd", "icem"],
    "ansys icem cfd": ["icem cfd", "ansys icem", "icem"],
    "icem": ["icem cfd", "ansys icem", "ansys icem cfd"],
    "paraview": ["para view"],
    "para view": ["paraview"],
    "tecplot": ["tec plot"],
    "tec plot": ["tecplot"],
    # Turbulence / CFD models
    "rans": ["reynolds averaged navier stokes", "reynolds-averaged navier-stokes"],
    "reynolds averaged navier stokes": ["rans", "reynolds-averaged navier-stokes"],
    "reynolds-averaged navier-stokes": ["rans", "reynolds averaged navier stokes"],
    "les": ["large eddy simulation", "large-eddy simulation"],
    "large eddy simulation": ["les", "large-eddy simulation"],
    "large-eddy simulation": ["les", "large eddy simulation"],
    "dns": ["direct numerical simulation"],
    "direct numerical simulation": ["dns"],
    "k omega": ["k-omega", "kω", "k ω"],
    "k-omega": ["k omega", "kω", "k ω"],
    "k epsilon": ["k-epsilon", "kε", "k ε"],
    "k-epsilon": ["k epsilon", "kε", "k ε"],
    "sst": ["k-omega sst", "k omega sst", "sst k-omega"],
    "k-omega sst": ["sst", "k omega sst", "sst k-omega"],
    "spalart allmaras": ["spalart-allmaras", "sa model"],
    "spalart-allmaras": ["spalart allmaras", "sa model"],
    "sa model": ["spalart allmaras", "spalart-allmaras"],
    "transition model": ["transition modeling", "transition modelling"],
    "transition modeling": ["transition model", "transition modelling"],
    "transition modelling": ["transition model", "transition modeling"],
    # Solvers / CFD numerics
    "simple": ["simple algorithm"],
    "simple algorithm": ["simple"],
    "piso": ["piso algorithm"],
    "piso algorithm": ["piso"],
    "pimple": ["pimple algorithm"],
    "pimple algorithm": ["pimple"],
    "wall function": ["wall functions"],
    "wall functions": ["wall function"],
    "y+": ["y plus", "yplus"],
    "y plus": ["y+", "yplus"],
    "yplus": ["y+", "y plus"],
    # CFD domains
    "abl": ["atmospheric boundary layer"],
    "atmospheric boundary layer": ["abl"],
    "wind resource": ["wind-resource"],
    "wind-resource": ["wind resource"],
    "wind farm": ["wind-farm"],
    "wind-farm": ["wind farm"],
    "airfoil": ["aerofoil"],
    "aerofoil": ["airfoil"],
    "multi phase": ["multiphase", "multi-phase"],
    "multiphase": ["multi phase", "multi-phase"],
    "multi-phase": ["multi phase", "multiphase"],
    "heat transfer": ["thermal analysis"],
    "thermal analysis": ["heat transfer"],
}
