from pydantic import BaseModel, ConfigDict, Field

from job_triage.db.models import BaseResume
from job_triage.job_assess.schemas import (
    EmploymentType,
    EngagementType,
    LocationConstraint,
    Priority,
    RoleFamily,
    SeniorityLevel,
    WorkArrangement,
)
from job_triage.schemas import LLMRunMetadata


class ApplicationContext(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    assessed_content_hash: str
    location: LocationConstraint

    title: str
    company: str
    job_description: str
    date_posted: str
    source_url: str
    metadata_text: dict[str, str] = Field(default_factory=dict)


class JobApplication(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    job_id: int
    base_resume: BaseResume
    final_score: int
    assessed_content_hash: str


class JobApplicationInfo(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    job_id: int
    base_resume: BaseResume
    final_score: int
    source_json: str
    source_url: str
    title: str
    assessed_content_hash: str
    location: LocationConstraint


class SelectedProject(BaseModel):
    """Selected project ID to include in a tailored resume."""

    project_id: str


class ExperienceBullet(BaseModel):
    """Selected experience bullet ID to include in a tailored resume."""

    bullet_id: str


class SelectedExperience(BaseModel):
    """Selected experience role key to include in a tailored resume."""

    role_key: str
    bullets: list[ExperienceBullet]


class CoreSkillGroup(BaseModel):
    """Selected core skill group name to include in a tailored resume."""

    group_name: str


class LLMApplicationPlan(BaseModel):
    """Structured resume-tailoring plan generated from application context.

    The plan selects which trusted resume sections and points to render.
    """

    model_config = ConfigDict(frozen=True)

    tailored_summary: str
    core_skills: list[CoreSkillGroup]
    selected_experience: list[SelectedExperience]
    selected_projects: list[SelectedProject]


class ExperienceSelection(BaseModel):
    """Selected experience entry to include in a tailored resume."""

    years: str
    company: str
    job_title: str
    bullets: list[str]


class ProjectSelection(BaseModel):
    """Selected project entry to include in a tailored resume."""

    label: str
    description: str


class CoreSkillsSelection(BaseModel):
    """Selected core skills entry to include in a tailored resume."""

    group_name: str
    skills_list: str


class ApplicationPlan(BaseModel):
    """Structured resume-tailoring plan generated from application context.

    The plan selects which trusted resume sections to render and supplies
    positioning text. Fixed factual inventories, such as AI work history, stay
    in the renderer instead of being generated by the model.
    """

    tailored_summary: str
    core_skills: list[CoreSkillsSelection]
    selected_experience: list[ExperienceSelection]
    selected_projects: list[ProjectSelection]
    metadata: LLMRunMetadata | None = None


class ApplicationJobPost(BaseModel):

    model_config = ConfigDict(frozen=True)

    title: str
    job_description: str
    metadata_text: dict[str, str] = Field(default_factory=dict)


class ResumeContext(BaseModel):

    model_config = ConfigDict(frozen=True)

    post: ApplicationJobPost
    stack_mentions: list[str]


class ApplicationProse(BaseModel):

    summary: str
    cover_letter_text: str


class ResumePlan(BaseModel):

    core_skills: list[CoreSkillsSelection]
    selected_experience: list[ExperienceSelection]
    selected_projects: list[ProjectSelection]
    metadata: LLMRunMetadata | None = None


class StackComparison(BaseModel):
    model_config = ConfigDict(frozen=True)

    skill: str
    required_score: int
    my_score: int
    priority: Priority = Field(
        description=(
            "Classify the skill's importance from the extracted priority_text only:\n"
            "- 'required': Explicitly mandatory, required, essential, or a must-have.\n"
            "- 'highly_preferred': Strongly requested or highlighted as a massive advantage (e.g., 'strongly preferred', 'highly desired').\n"
            "- 'preferred': Standard asset or desired qualification (e.g., 'preferred', 'important', 'desirable', 'should have').\n"
            "- 'bonus': Framed as a 'plus', 'nice-to-have', or extra advantage.\n"
            "- 'not_required': Explicitly mentioned but stated as not required (e.g., 'No prior ML knowledge needed')."
        )
    )


class ApplicationFitContext(BaseModel):

    model_config = ConfigDict(frozen=True)

    stack_assessments: list[StackComparison]
    location_constraint: LocationConstraint
    engagement_type: EngagementType
    employment_type: EmploymentType
    work_arrangement: WorkArrangement
    seniority: SeniorityLevel  # Lead positions will be discarded.
    role_family: RoleFamily


class ProseContext(BaseModel):

    model_config = ConfigDict(frozen=True)

    post: ApplicationJobPost
    assessment: ApplicationFitContext
    resume_plan: ResumePlan
