from pydantic import BaseModel, ConfigDict, Field

from job_triage.db.models import BaseResume
from job_triage.job_assess.schemas import (
    EmploymentType,
    EngagementType,
    LocationConstraint,
    Priority,
    RoleFamily,
    SeniorityLevel,
    WorkArrangement,
)
from job_triage.schemas import LLMRunMetadata


class ApplicationContext(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    assessed_content_hash: str
    location: LocationConstraint

    title: str
    company: str
    job_description: str
    date_posted: str
    source_url: str
    metadata_text: dict[str, str] = Field(default_factory=dict)


class JobApplication(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    job_id: int
    base_resume: BaseResume
    final_score: int
    assessed_content_hash: str


class JobApplicationInfo(BaseModel):
    """Data needed to generate application materials for one job."""

    model_config = ConfigDict(frozen=True)

    job_id: int
    base_resume: BaseResume
    final_score: int
    source_json: str
    source_url: str
    title: str
    assessed_content_hash: str
    location: LocationConstraint


class SelectedProject(BaseModel):
    """Selected project ID to include in a tailored resume."""

    project_id: str


class PlannedProject(BaseModel):
    """Selected project entry to include in a tailored resume."""

    label: str
    description: str


class SelectedExperienceBullet(BaseModel):
    """Selected experience bullet ID to include in a tailored resume."""

    bullet_id: str


class PlannedExperienceBullet(BaseModel):
    """Selected experience bullet ID to include in a tailored resume."""

    description: str


class SelectedExperience(BaseModel):
    """Selected experience role key to include in a tailored resume."""

    role_key: str
    bullets: list[SelectedExperienceBullet]


class PlannedExperience(BaseModel):
    """Selected experience entry to include in a tailored resume."""

    years: str
    company: str
    job_title: str
    bullets: list[PlannedExperienceBullet]


class SelectedCoreSkill(BaseModel):
    """Selected core skill group name to include in a tailored resume."""

    group_name: str


class PlannedCoreSkills(SelectedCoreSkill):
    """Selected core skills entry to include in a tailored resume."""

    skills_list: str


class LLMSelectedResume(BaseModel):
    """Resume inventory IDs selected by the LLM before local expansion."""

    model_config = ConfigDict(frozen=True)

    core_skills: list[SelectedCoreSkill]
    selected_experience: list[SelectedExperience]
    selected_projects: list[SelectedProject]


class SelectedResume(LLMSelectedResume):
    """LLM-selected resume inventory IDs with run metadata."""

    model_config = ConfigDict(frozen=True)

    metadata: LLMRunMetadata | None = None


class LLMPlannedResume(BaseModel):
    """Renderable resume sections after selected IDs are mapped to content."""

    core_skills: list[PlannedCoreSkills]
    selected_experience: list[PlannedExperience]
    selected_projects: list[PlannedProject]


class PlannedResume(LLMPlannedResume):
    """Renderable resume sections with run metadata."""

    metadata: LLMRunMetadata | None = None


class ApplicationJobPost(BaseModel):
    """Job post fields needed by the application-material workflow."""

    model_config = ConfigDict(frozen=True)

    title: str
    job_description: str
    metadata_text: dict[str, str] = Field(default_factory=dict)


class ResumeContext(BaseModel):
    """Context sent to the resume-selection LLM."""

    model_config = ConfigDict(frozen=True)

    post: ApplicationJobPost
    stack_mentions: list[str]


class LLMApplicationProse(BaseModel):
    """Application prose generated by the LLM."""

    summary: str
    cover_letter_text: str


class ApplicationProse(LLMApplicationProse):
    """Application prose with run metadata."""

    metadata: LLMRunMetadata | None = None


class StackComparison(BaseModel):
    model_config = ConfigDict(frozen=True)

    skill: str
    skill_fit: float
    priority: Priority = Field(
        description=(
            "Classify the skill's importance from the extracted priority_text only:\n"
            "- 'required': Explicitly mandatory, required, essential, or a must-have.\n"
            "- 'highly_preferred': Strongly requested or highlighted as a massive advantage (e.g., 'strongly preferred', 'highly desired').\n"
            "- 'preferred': Standard asset or desired qualification (e.g., 'preferred', 'important', 'desirable', 'should have').\n"
            "- 'bonus': Framed as a 'plus', 'nice-to-have', or extra advantage.\n"
            "- 'not_required': Explicitly mentioned but stated as not required (e.g., 'No prior ML knowledge needed')."
        )
    )


class ApplicationFitContext(BaseModel):
    """Assessment context used when generating application prose."""

    model_config = ConfigDict(frozen=True)

    stack_comparisons: list[StackComparison]
    location_constraint: LocationConstraint
    engagement_type: EngagementType
    employment_type: EmploymentType
    work_arrangement: WorkArrangement
    seniority: SeniorityLevel  # Lead positions will be discarded.
    role_family: RoleFamily


class ProseContext(BaseModel):
    """Context sent to the application-prose LLM."""

    model_config = ConfigDict(frozen=True)

    post: ApplicationJobPost
    assessment: ApplicationFitContext
    resume_plan: LLMPlannedResume
