"""Initial creation

Revision ID: 055aec76ff62
Revises: 
Create Date: 2026-06-16 14:15:35.852104

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "055aec76ff62"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ats_boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("board_slug", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ats_boards")),
        sa.UniqueConstraint(
            "provider", "board_slug", name="uq_ats_boards_provider_board_slug"
        ),
    )
    op.create_table(
        "raw_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ats_board_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("date_posted", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_applied", sa.Boolean(), nullable=False),
        sa.Column("provider_payload_json", sa.Text(), nullable=False),
        sa.Column("normalized_metadata_json", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["ats_board_id"],
            ["ats_boards.id"],
            name=op.f("fk_raw_jobs_ats_board_id_ats_boards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_jobs")),
        sa.UniqueConstraint(
            "ats_board_id", "external_id", name="uq_raw_jobs_ats_board_id_external_id"
        ),
        sa.UniqueConstraint("source_url", name=op.f("uq_raw_jobs_source_url")),
    )
    op.create_table(
        "job_score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_job_id", sa.Integer(), nullable=False),
        sa.Column("assessed_content_hash", sa.String(length=64), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_job_id"],
            ["raw_jobs.id"],
            name=op.f("fk_job_score_raw_job_id_raw_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_score")),
        sa.UniqueConstraint("raw_job_id", name=op.f("uq_job_score_raw_job_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_score")
    op.drop_table("raw_jobs")
    op.drop_table("ats_boards")
    # ### end Alembic commands ###
